#define SYMBOL_TYPE_VARIABLE 300
#define SYMBOL_TYPE_FUNCTION 301

#define ERROR_CODE (-100)

#define SYMBOLS_HASH_TABLE_CAPACITY 500

#define EXIT_CODE_SUCCESS 0
#define EXIT_CODE_WRONG_ARGUMENTS (-1000)
#define EXIT_CODE_UNABLE_TO_OPEN_FILE (-1001)
#define EXIT_CODE_UNABLE_TO_OPEN_KEYWORDS_DB (-1003)

#define ANSI_COLOR_ERROR "\x1b[31m"
#define ANSI_COLOR_RESET "\x1b[0m"