#define SYMBOL_TYPE_VARIABLE 300
#define SYMBOL_TYPE_FUNCTION 301

#define WELCOME_MESSAGE_FILE "txt/welcome.txt"
#define HELP_MESSAGE_FILE "txt/help.txt"

#define CALLABILITY_SYMBOL_NOT_FOUND 400
#define CALLABILITY_SYMBOL_NOT_FUNCTION 401
#define CALLABILITY_ARGUMENT_COUNT_MISMATCH 402
#define CALLABILITY_CALLABLE 403

#define SYMBOLS_HASH_TABLE_CAPACITY 500

#define EXIT_CODE_SUCCESS 0
#define EXIT_CODE_WRONG_ARGUMENTS (-1000)
#define EXIT_CODE_UNABLE_TO_OPEN_FILE (-1001)
#define EXIT_CODE_UNABLE_TO_OPEN_KEYWORDS_DB (-1003)

#define ANSI_COLOR_ERROR "\x1b[31m"
#define ANSI_COLOR_RESET "\x1b[0m"